-- MySQL Script generated by MySQL Workbench
-- mié 20 nov 2019 23:14:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tpfinaldb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tpfinaldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tpfinaldb` DEFAULT CHARACTER SET utf8 ;
USE `tpfinaldb` ;

-- -----------------------------------------------------
-- Table `tpfinaldb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`categoria` (
  `id_cat` INT(11) NOT NULL,
  `descripcion_cat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`contenido` (
  `id_contenido` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `fec_publicacion` DATETIME NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contenido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`comentario` (
  `id_comentario` INT(11) NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion_comentario` VARCHAR(45) NOT NULL,
  `apodo` VARCHAR(45) NOT NULL,
  `id_contenido` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_Comentario_Contenido1_idx` (`id_contenido` ASC),
  CONSTRAINT `fk_Comentario_Contenido1`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `tpfinaldb`.`contenido` (`id_contenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`corresponde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`corresponde` (
  `id_contenido_descargable` INT(11) NOT NULL,
  `id_cat` INT(11) NOT NULL,
  PRIMARY KEY (`id_contenido_descargable`, `id_cat`),
  INDEX `fk_Contenido_has_Categoria_Categoria1_idx` (`id_cat` ASC),
  INDEX `fk_Contenido_has_Categoria_Contenido1_idx` (`id_contenido_descargable` ASC),
  CONSTRAINT `fk_Contenido_has_Categoria_Categoria1`
    FOREIGN KEY (`id_cat`)
    REFERENCES `tpfinaldb`.`categoria` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contenido_has_Categoria_Contenido1`
    FOREIGN KEY (`id_contenido_descargable`)
    REFERENCES `tpfinaldb`.`contenido` (`id_contenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`descargable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`descargable` (
  `id_contenido_descargable` INT(11) NOT NULL,
  PRIMARY KEY (`id_contenido_descargable`),
  CONSTRAINT `fk_Descargable_Contenido`
    FOREIGN KEY (`id_contenido_descargable`)
    REFERENCES `tpfinaldb`.`contenido` (`id_contenido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`usuario` (
  `id_usuario` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fec_nac` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`descarga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`descarga` (
  `id_usuario` INT(11) NOT NULL,
  `id_contenido_descargable` INT(11) NOT NULL,
  `velocidad` VARCHAR(45) NULL DEFAULT NULL,
  `id_descarga` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`, `id_contenido_descargable`),
  INDEX `fk_Usuario_has_Descargable_Descargable1_idx` (`id_contenido_descargable` ASC),
  INDEX `fk_Usuario_has_Descargable_Usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Usuario_has_Descargable_Descargable1`
    FOREIGN KEY (`id_contenido_descargable`)
    REFERENCES `tpfinaldb`.`descargable` (`id_contenido_descargable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Descargable_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tpfinaldb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`encuesta` (
  `id_encuesta` INT(11) NOT NULL,
  `resumen_positivo` VARCHAR(45) NOT NULL,
  `resumen_negativo` VARCHAR(45) NOT NULL,
  `Descarga_id_usuario` INT(11) NULL DEFAULT NULL,
  `Descarga_id_contenido_descargable` INT(11) NULL DEFAULT NULL,
  `puntaje` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_encuesta`),
  INDEX `fk_Encuesta_Descarga1_idx` (`Descarga_id_usuario` ASC, `Descarga_id_contenido_descargable` ASC),
  CONSTRAINT `fk_Encuesta_Descarga1`
    FOREIGN KEY (`Descarga_id_usuario` , `Descarga_id_contenido_descargable`)
    REFERENCES `tpfinaldb`.`descarga` (`id_usuario` , `id_contenido_descargable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`replica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`replica` (
  `id_replica` INT(11) NOT NULL,
  `apodo` VARCHAR(45) NOT NULL,
  `detalle` VARCHAR(45) NOT NULL,
  `id_comentario` INT(11) NULL DEFAULT NULL,
  `id_replica_precede` INT(11) NOT NULL,
  PRIMARY KEY (`id_replica`),
  INDEX `fk_Replica_Comentario1_idx` (`id_comentario` ASC),
  INDEX `fk_Replica_Replica1_idx` (`id_replica_precede` ASC),
  CONSTRAINT `fk_Replica_Comentario1`
    FOREIGN KEY (`id_comentario`)
    REFERENCES `tpfinaldb`.`comentario` (`id_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Replica_Replica1`
    FOREIGN KEY (`id_replica_precede`)
    REFERENCES `tpfinaldb`.`replica` (`id_replica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`reproducible`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`reproducible` (
  `id_contenido_reproducible` INT(11) NOT NULL,
  PRIMARY KEY (`id_contenido_reproducible`),
  CONSTRAINT `fk_Reproducible_Contenido1`
    FOREIGN KEY (`id_contenido_reproducible`)
    REFERENCES `tpfinaldb`.`contenido` (`id_contenido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tpfinaldb`.`reproduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tpfinaldb`.`reproduccion` (
  `id_reproduccion` INT(11) NOT NULL,
  `fecha_ini` DATE NOT NULL,
  `hora_ini` VARCHAR(5) NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `hora_fin` VARCHAR(5) NOT NULL,
  `sistema_operativo` VARCHAR(45) NOT NULL,
  `id_contenido_reproducible` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_reproduccion`),
  INDEX `fk_Reproduccion_Reproducible1_idx` (`id_contenido_reproducible` ASC),
  CONSTRAINT `fk_Reproduccion_Reproducible1`
    FOREIGN KEY (`id_contenido_reproducible`)
    REFERENCES `tpfinaldb`.`reproducible` (`id_contenido_reproducible`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `tpfinaldb` ;

-- -----------------------------------------------------
-- procedure INS_CONTENIDO
-- -----------------------------------------------------

DELIMITER $$
USE `tpfinaldb`$$

--
-- Funciones
--
DROP FUNCTION IF EXISTS `IFEMPTY`$$
CREATE DEFINER=`root`@`localhost` FUNCTION `IFEMPTY` (`s` INT, `defaultValue` INT) RETURNS INT(11) return if(s is null or s = '', defaultValue, s)$$


CREATE DEFINER=`root`@`localhost` PROCEDURE `INS_CONTENIDO`(in unTitulo varchar(45), in unaFecha DATETIME, in unaExt VARCHAR(45), in unTipo VARCHAR(45), in unaDescr VARCHAR(1000), IN `unaImg` VARCHAR(255))
BEGIN
	DECLARE id int;
    set id = (SELECT IFEMPTY(max(id_contenido), 0)+1 FROM tpfinaldb.contenido);

	INSERT INTO tpfinaldb.contenido (id_contenido,titulo,fec_publicacion,extension,tipo, descripcion, image) 
    VALUES (id, unTitulo, unaFecha, unaExt, unTipo, unaDescr, unaImg);
    
    if(unTipo="reproducible")
		THEN
			INSERT INTO tpfinaldb.reproducible values (id);
		ELSE
			INSERT INTO tpfinaldb.descargable values (id);
	end if;
END$$



DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
